'use strict'

define(function () {
  return {
    'Argentina': 'ar',
    'Algeria': 'dz',
    'Australia': 'au',
    'Belgium': 'be',
    'Bosnia and Herzegovina': 'ba',
    'Bosnia & Herzegovina': 'ba',
    'Brazil': 'br',
    'Cameroon': 'cm',
    'Chile': 'cl',
    'Colombia': 'co',
    'Columbia': 'co',
    'Costa Rica': 'cr',
    'Croatia': 'hr',
    'Ecuador': 'ec',
    'England': '_England',
    'France': 'fr',
    'Germany': 'de',
    'Ghana': 'gh',
    'Greece': 'gr',
    'Honduras': 'hn',
    'Iran': 'ir',
    'Italy': 'it',
    'Ivory Coast': 'ci',
    'Japan': 'jp',
    'Korea Republic': 'kr',
    'Mexico': 'mx',
    'Netherlands': 'nl',
    'Nigeria': 'ng',
    'Portugal': 'pt',
    'Russia': 'ru',
    'Spain': 'es',
    'South Korea': 'kr',
    'Switzerland': 'ch',
    'Uruguay': 'uy',
    'United States': 'us',
    'USA': 'us'
  };
});
